apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: zalando
  namespace: operators
spec:
  interval: 1m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: operators
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: '1.8.2'
      sourceRef:
        kind: HelmRepository
        name: zalando
        namespace: operators
      interval: 1m
  values:
    configKubernetes:
      enable_cross_namespace_secret: true
    resources:
      requests:
        memory: 32Mi