---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  filterTags:
    extract: version
    pattern: (?P<version>.*)-fpm-alpine
  imageRepositoryRef:
    name: nextcloud
  policy:
    semver:
      range: '>=24.0.0 <25.0.0'

