---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: (?P<version>.*)-alpine
  imageRepositoryRef:
    name: nginx
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'

