apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.2.3'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1m
  values:
    controller:
  # A replica count of minimum 2 ensures high availability for Nginx Ingress main application Pods
      replicaCount: 2
      service:
        type: LoadBalancer

  ## Enable the metrics of the NGINX Ingress controller https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/
      metrics:
        enabled: true
      podAnnotations:
        controller:
          metrics:
            service:
              servicePort: "9090"
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"