---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    config.linkerd.io/admission-webhooks: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-log-format: json
    config.linkerd.io/proxy-log-level: warn
    config.linkerd.io/proxy-cpu-limit: 10m
    config.linkerd.io/proxy-cpu-request: 5m
    config.linkerd.io/proxy-memory-limit: 64Mi
    config.linkerd.io/proxy-memory-request: 32Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-log-format: json
    config.linkerd.io/proxy-log-level: warn
    config.linkerd.io/proxy-cpu-limit: 10m
    config.linkerd.io/proxy-cpu-request: 5m
    config.linkerd.io/proxy-memory-limit: 64Mi
    config.linkerd.io/proxy-memory-request: 32Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-log-format: json
    config.linkerd.io/proxy-log-level: warn
    config.linkerd.io/proxy-cpu-limit: 10m
    config.linkerd.io/proxy-cpu-request: 5m
    config.linkerd.io/proxy-memory-limit: 64Mi
    config.linkerd.io/proxy-memory-request: 32Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/proxy-log-format: json
    config.linkerd.io/proxy-log-level: warn
    config.linkerd.io/proxy-cpu-limit: 10m
    config.linkerd.io/proxy-cpu-request: 5m
    config.linkerd.io/proxy-memory-limit: 64Mi
    config.linkerd.io/proxy-memory-request: 32Mi