apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic
  namespace: operators
spec:
  interval: 1m
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: operators
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: '3.8.2'
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: operators
      interval: 1m
  values:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi