apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server.yaml
  - elastic-operator.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - filebeat-logs.yaml
  - metricbeat-k8-nodes.yaml