apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opstree
  namespace: operators
spec:
  interval: 1m
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: operators
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: '>=0.11.0 <1.0.0'
      sourceRef:
        kind: HelmRepository
        name: opstree
        namespace: operators
      interval: 1m
  values:
    resources:
      requests: 
        cpu: 20m
        memory: 32Mi