apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: infrastructure-pg-cluster
  namespace: database
spec:
  teamId: infrastructure
  volume:
    size: 5Gi
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 500Mi
  numberOfInstances: 1
  users:
    # database owner
    me:
    - superuser
    - createdb
    - createrole
    - login

    # role for application foo
    apps.nextcloud: 
    - login
    - createrole

  #databases: name->owner
  databases:
    nextcloud: apps.nextcloud
  postgresql:
    version: "14"
    parameters:
      password_encryption: scram-sha-256
