apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: private-overlays
    namespace: flux-system
spec:
    interval: 1m30s
    ref:
        branch: main
    secretRef:
      name: private-overlays-auth
    url: ssh://git@github.com/elliottpope/homecloud-private
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-overlays
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-overlays-reconciler
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:apps:reconciler
- kind: ServiceAccount
  name: private-overlays
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-issuer-updater
  namespace: cert-manager
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-overlays-cert-updater
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-issuer-updater
subjects:
- kind: ServiceAccount
  name: private-overlays
  namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: private-overlays
    namespace: flux-system
spec:
    interval: 1m0s
    path: ./
    prune: false
    serviceAccountName: private-overlays
    sourceRef:
        kind: GitRepository
        name: private-overlays
        namespace: flux-system
